### ISSUE TITLE
Critic test may fail

### ISSUE THREAD

**Issue by eserte** [perl-weasel/weasel#1]
See http://analysis.cpantesters.org/solved?distv=Weasel-0.05 for some more information.

It's possible that this happens only if the Perl::Critic::Nits module is installed.

**Comment by ehuelsmann** [comment]
@eserte yes, it only happens when Perl::Critic::Nits is installed, because that checks for cross module use of "internal identifiers" (identifiers starting with an underscore). I'm not sure what to do about it because the policy that ::Nits uses doesn't seem to allow white listing.

The thing is that I'm using an internal identifier which was explicitly created to be used between the Entity and the Session modules. Other modules should respect the contract.
